### ISSUE TITLE
Performance issues in test execution (ng test)​

### ISSUE THREAD

**Issue by olgapuig** [systelab/seed-angular#49]
We do have performance issues in the test execution in some projects. 
The seed-angular is working fine but we need to share the best practices on how to configure the project in order to avoid it.

**Comment by rochiebcn** [comment]
Hi @olgapuig
There are some common mistakes that could cause memory leaks or similar problems. To avoid these type of issues some good practices are:

- **Execute the tests with Chrome in mode headless**. In karma.conf.js: `browsers:                 ['ChromeHeadless']`
- **Avoid the use of services**. Use mock objects for these services. 
_Example:_
```
providers: [
				{ provide: DialogService, useFactory: dialogServiceStub },
				{ provide: MessagePopupService, useFactory: messagePopupServiceStub },
				{ provide: WorklistService, useFactory: worklistServiceStub },
			]
```

where worklistServiceStub is a constant like this: `const worklistServiceStub = () => ({ sendToMyLIS: worklistId => ({}) });`

- **Don't use inject to inject a service in a test class.** Use TestBed.get(MyService). This is very usual in tests of services 
- **Use the library ng-cache-testing-module at the beginning of the spec file.** In tests files of complex components in each test execution all the component has needs to be recreated, this cause a slow performance for multiple tests in one spec file. _Example:_
```
describe('Component complex Test', () => {
	cacheTestingModule();
```

- **Use the library karma-parallel.** Another solution for increase the speed of a suite of tests is to use the library karma-parallel to execute the tests in parallel mode. If exists a big suite of tests created could be difficult to apply this solution, due it's probably that we have too much coupling between tests of one spec file
- **Use the NO_ERRORS_SCHEMA** in the configuration of the test component. If we use NO_ERRORS_SCHEMA we avoid loading all the components related to our component to test, due the test will not check the template file. This is very useful if we are focusing in test the business logic of one component. 
_Example:_
```
TestBed.configureTestingModule({
			schemas:      [NO_ERRORS_SCHEMA],
```
