### ISSUE TITLE
e2e - Fix issue with protractorv5.4.4, ag-gridv24 and Angularv10

### ISSUE THREAD

**Issue by olgapuig** [systelab/seed-angular#50]
The e2e test execution is locked after clicking on an ag-grid row, and then a new dialog must be displayed.
This issue was found by the Modulab team last September.

Versions:
- protractorv5.4.4
- ag-gridv24
- Angularv10
- Chrome version > 83

It was tried to solve with the async/await but it didn't work. 
And then, updating the browserlist and dependencies with the following command
npx browserslist@latest --update-db

This needs to be investigated and the solution needs to be applied into the seed-angular as a reference for all the projects.

**Comment by atzurk** [comment]
Tested in seed-angular: PASS
Tested in modulab branch with updated protractor and systelab-component-test: FAIL
